### ISSUE TITLE
Please add Java

### ISSUE THREAD

**Issue by vitaly-zdanevich** [mattboehm/vim-unstack#33]
Example stack trace:

```
Exception in thread "main" marytts.exceptions.MaryConfigurationException: Cannot start MARY server
	at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:66)
	at Txt2Wav.main(Txt2Wav.java:12)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 2
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3410)
	at java.base/java.lang.String.substring(String.java:1883)
	at marytts.server.EnvironmentChecks.check(EnvironmentChecks.java:46)
	at marytts.server.Mary.startup(Mary.java:286)
	at marytts.server.Mary.startup(Mary.java:204)
	at marytts.util.MaryRuntimeUtils.ensureMaryStarted(MaryRuntimeUtils.java:72)
	at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:64)
	... 1 more
```

**Comment by mattboehm** [comment]
Thanks for the suggestion. This will be tricky to do, as the code currently uses a regex to find the file path, but these stack traces do not contain the file path. I will take a look at the code to see how easily it can be refactored to support this.

**Comment by DmitrySandalov** [comment]
https://github.com/simonhicks/stacktrace.vim/blob/master/autoload/stacktrace.vim
